
#ifndef HAL_PUSH_BUTTON_PUSH_BUTTON_H_
#define HAL_PUSH_BUTTON_PUSH_BUTTON_H_

#define BUTTON_PORT		DIO_PORTD
#define BUTTON_PIN			PIN2

u8 BUTTON_Init();


#endif /* HAL_PUSH_BUTTON_PUSH_BUTTON_H_ */
